backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "rules"
    label: "Правила"
    folder: "content/rules"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Текст", name: "body", widget: "markdown" }

  - name: "news"
    label: "Новости"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Изображение", name: "image", widget: "image" }
      - { label: "Текст", name: "body", widget: "markdown" }

  - name: "wiki"
    label: "Википедия"
    folder: "content/wiki"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Фото", name: "image", widget: "image" }
      - { label: "Описание", name: "body", widget: "markdown" }
